syntax = "LuaJIT"
column_width = 100
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 4
quote_style = "AutoPreferSingle"
call_parentheses = "NoSingleTable"
space_after_function_names = "Never"
collapse_simple_statement = "Always"
